// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBduUl9FLWBzy_sHa0F6Y7fE5F5MTmzdqo',
    appId: '1:200884864027:web:3df02bf964214f9be2a4be',
    messagingSenderId: '200884864027',
    projectId: 'food-ordering-app-f89c6',
    authDomain: 'food-ordering-app-f89c6.firebaseapp.com',
    storageBucket: 'food-ordering-app-f89c6.appspot.com',
    measurementId: 'G-9NL2HBX1PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwugQdhrk7J52ZDPcy3CBDF8s-WOQZ3A',
    appId: '1:200884864027:android:51b8754922da0811e2a4be',
    messagingSenderId: '200884864027',
    projectId: 'food-ordering-app-f89c6',
    storageBucket: 'food-ordering-app-f89c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjCKVVq4sGyROpN-CapT3CcZ3vCThWIKo',
    appId: '1:200884864027:ios:f91f044ffa6517e7e2a4be',
    messagingSenderId: '200884864027',
    projectId: 'food-ordering-app-f89c6',
    storageBucket: 'food-ordering-app-f89c6.appspot.com',
    androidClientId: '200884864027-0irdegj0tn5m5qvpbkqdcelmrl6tnvfj.apps.googleusercontent.com',
    iosClientId: '200884864027-sl0q82ap6v705utckjgl8dcu7gtqir7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjCKVVq4sGyROpN-CapT3CcZ3vCThWIKo',
    appId: '1:200884864027:ios:f91f044ffa6517e7e2a4be',
    messagingSenderId: '200884864027',
    projectId: 'food-ordering-app-f89c6',
    storageBucket: 'food-ordering-app-f89c6.appspot.com',
    androidClientId: '200884864027-0irdegj0tn5m5qvpbkqdcelmrl6tnvfj.apps.googleusercontent.com',
    iosClientId: '200884864027-sl0q82ap6v705utckjgl8dcu7gtqir7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiHfS4Ujr9g_2u-mAHIFosBtsIpM3QJcY',
    appId: '1:200884864027:web:3de1cbb4831634e2e2a4be',
    messagingSenderId: '200884864027',
    projectId: 'food-ordering-app-f89c6',
    authDomain: 'food-ordering-app-f89c6.firebaseapp.com',
    storageBucket: 'food-ordering-app-f89c6.appspot.com',
    measurementId: 'G-LX31GF1CJV',
  );
}
